language: objective-c
xcode_project: activity_keyBoard.xcodeproj
xcode_scheme: activity_keyBoard
osx_image: xcode7.3
branch:
  only:
  - master
notifications:
  email: false

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
